name: Docker Build

on:
  push:
    branches:
      - arm32

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #
      # Checkout
      #
      - name: checkout code
        uses: actions/checkout@v3
      #
      # Setup QEMU
      #
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      #
      # Setup Buildx
      #
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      #
      # Build
      #
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          context: .
          platforms: linux/arm/v7
          push: true
          tags: ghcr.io/urbancmc/crfpp:nightly