name: Docker ARM Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #
      # Checkout
      #
      - name: checkout code
        uses: actions/checkout@v2
      #
      # Setup QEMU
      #
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      #
      # Setup Buildx
      #
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      #
      # Login to Docker Hub
      #
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #
      # Build
      #
      - name: build the image
        run: |
          docker build --push --no-cache \
            --build-arg BUILD_ARCH=aarch64-unknown-linux-gnu \
            --tag hkotel/crfpp:latest-arm \
            --platform linux/arm64 .
